### obtener todas las canciones
GET http://localhost:3000/api/canciones


### obtener una cancion
GET http://localhost:3000/api/canciones/651ec1d589c709f42ee3ff5f

### crear un nueva cancion 
POST http://localhost:3000/api/canciones/
Content-Type: application/json

{
  "nombre": "LALAA",
  "cantante":"Myke Tower"
}
### modificar una cancion (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/canciones/651ec2e13cb3bf1c7b75f558
Content-Type: application/json

{
  "nombre": "bzrp #53"
}

### modificar una cancion (PATCH - recurso parcial)
PATCH http://localhost:3000/api/canciones/651ec2e13cb3bf1c7b75f558
Content-Type: application/json

{
  "nombre": "kou",
  "cantante": "Valen"
}

### borrar una cancion
DELETE http://localhost:3000/api/canciones/652491dccd89407620a7630b